---
- name: reboot
  block:
    - name: schedule reboot
      ansible.builtin.shell: |
        sleep 1
        reboot
      async: 1000000000
      poll: 0
      failed_when: false
      changed_when: true

    - name: wait for server to come back up
      ansible.builtin.wait_for_connection:
        delay: 60
