---

- include: variables.yml

- include: install.yml

- include: configure.yml

- name: main | ensure postgresql is running
  meta: flush_handlers

- include: replication.yml

# - include: healthchecks.yml
