---
- name: cyverse.irods_cfg
  src: https://github.com/CyVerse-Ansible/ansible-irods-cfg
  version: f091a4e8cb7274116a4defd8b8d2f0fc594d3cbe

- name: cyverse.rabbitmq_vhost
  src: https://github.com/CyVerse-Ansible/ansible-rabbitmq-vhost
  version: 07783cde3a7924c0404b650210447f81a7469e41

- name: geerlingguy.apache
  src: geerlingguy.apache
