---
- hosts: "{{ hosts | default('all') }}"
  tasks:
    - name: display var1
      debug:
        var: var1 | default('inventory_hostname')

    - name: display var2
      debug:
        var: var2
      when: var2 is defined
