---
_dbms_irods_password: "{{ dbms_irods_password | mandatory }}"
_dbms_irods_user: "{{ dbms_irods_user | default('irods') }}"

_dbms_log_min_duration: "{{ dbms_log_min_duration | default(1000) }}"

_dbms_replication_password: "{{ dbms_replication_password | mandatory }}"
_dbms_replication_start: "{{ dbms_replication_start | default(false) }}"
_dbms_replication_user: "{{ dbms_replication_user | default('postgres') }}"
