---

# - hosts:
#     - primary_postgres_node
#     - secondary_postgres_nodes
#   roles:
#     - postgres12
#


# Here is the contents of iinventory/hosts in the following examples.
#
# [dbms_primary]
# ds-db1.cyverse.org
#
# [dbms_replicas]
# ds-db2.cyverse.org
#
# [dbms:children]
# dbms_primary
# dbms_replicas


# Example 1: Set up primary and replicas in separate plays.

- name: Set up primary DBMS
  hosts: dbms_primary
  become: true
  gather_facts: false
  roles:
    - role: postgres12
      vars:
        pg_downstream_nodes: "{{ groups['dbms_replicas'] }}"
        pg_shared_buffers: "{{ ansible_facts['ansible_memtotal_mb']|int / 4 }}MB"
        pg_effective_cache_size: "{{ ansible_facts['ansible_memtotal_mb']|int /2 }}MB"

- name: Set up replica DBMSs
  hosts: dbms_replicas
  become: true
  gather_facts: false
  roles:
    - role: postgres12
      vars:
        pg_upstream_node: "{{ groups['dbms_primary'][0] }}"
        pg_shared_buffers: "{{ ansible_facts['ansible_memtotal_mb']|int / 4 }}MB"
        pg_effective_cache_size: "{{ ansible_facts['ansible_memtotal_mb']|int / 2 }}MB"


# Example 2: Set up primary and replicas in a single play.

- name: Set up DBMS
  hosts: dbms
  become: true
  gather_facts: false
  roles:
    - role: postgres12
      vars:
        pg_downstream_nodes: "{{
          groups['dbms_replicas'] if ansible_hostname in groups['dbms_primary'] else [] }}"
        pg_upstream_node: "{{
          groups['dbms_primary'][0] if ansible_hostname in groups['dbms_replicas'] else None }}"
        pg_shared_buffers: "{{ ansible_facts['ansible_memtotal_mb']|int / 4 }}MB"
        pg_effective_cache_size: "{{ ansible_facts['ansible_memtotal_mb']|int /2 }}MB"
