---
- name: Prepare for PostgreSQL
  hosts: dbms
  become: true
  roles:
    - role: jtyr.grub_cmdline
      grub_cmdline_add_args:
        - transparent_hugepage=never
      tags:
        - no_testing

  post_tasks:
    - name: Add PostgreSQL yum repository
      yum_repository:
        name: pgdg-centos93
        description: PostgreSQL 9.3 yum repo for CentOS 6
        baseurl: https://download.postgresql.org/pub/repos/yum/9.3/redhat/rhel-6-x86_64/
        state: present

    - name: Install PostgreSQL server
      package:
        name: postgresql93-server

- name: Initialize PostgreSQL cluster
  hosts: dbms
  become: true
  become_user: postgres
  gather_facts: false
  tasks:
    - name: Initialize
      shell: |
        # TODO - This only checks for the existence of the database. It should be modified to
        # check whether or not the correct collate value is set.
        if ! [ -e /var/lib/pgsql/9.3/data/PG_VERSION ]
        then
          /usr/pgsql-9.3/bin/initdb --auth ident \
                                    --lc-collate C \
                                    --locale en_US.UTF-8 \
                                    --pgdata /var/lib/pgsql/9.3/data

          if [ "$?" -ne 0 ]
          then
            exit 1
          fi

          printf 'changed'
        fi
      register: result
      changed_when: result.stdout == 'changed'
  tags:
    - no_testing
