---

- name: Prepare for PostgreSQL
  hosts: dbms
  become: true
  roles:
    - role: adfinis_sygroup.grub
      grub_console: False
      grub_consoles: []
      grub_serial: []
      grub_timeout: 0
      grub_disable_network_predictable_interface_names: False
      grub_cmdline_linux_default_list:
        - maybe-ubiquity
        - transparent_hugepage=never
      tags:
        - no_testing

- name: Set up primary DBMS
  hosts: dbms_primary
  become: true
  gather_facts: false
  roles:
    - role: postgres12
      vars:
        pg_downstream_nodes: "{{ groups['dbms_replicas'] }}"
        pg_shared_buffers: "{{ (ansible_facts['memtotal_mb']|int / 4) | int }}MB"
        pg_effective_cache_size: "{{ (ansible_facts['memtotal_mb']|int /2) | int }}MB"

- name: Set up replica DBMSs
  hosts: dbms_replicas
  become: true
  gather_facts: false
  roles:
    - role: postgres12
      vars:
        pg_upstream_node: "{{ groups['dbms_primary'][0] }}"
        pg_shared_buffers: "{{ (ansible_facts['memtotal_mb']|int / 4) | int }}MB"
        pg_effective_cache_size: "{{ ansible_facts['memtotal_mb']|int // 2 }}MB"
