---

- name: Set up primary DBMS
  hosts: dbms_primary
  become: true
  roles:
    - role: postgres12
      vars:
        pg_downstream_nodes: "{{ groups['dbms_replicas'] }}"
        pg_shared_buffers: "{{ ansible_facts['ansible_memtotal_mb']|int / 4 }}MB"
        pg_effective_cache_size: "{{ ansible_facts['ansible_memtotal_mb']|int /2 }}MB"
  #gather_facts: false

- name: Set up replica DBMSs
  hosts: dbms_replicas
  become: true
  roles:
    - role: postgres12
      vars:
        pg_upstream_node: "{{ groups['dbms_primary'][0] }}"
        pg_shared_buffers: "{{ ansible_facts['ansible_memtotal_mb']|int / 4 }}MB"
        pg_effective_cache_size: "{{ ansible_facts['ansible_memtotal_mb']|int / 2 }}MB"
  #gather_facts: false
