---
- name: reload haproxy
  when: _full_os | bool
  service:
    name: rh-haproxy18-haproxy
    state: reloaded

- name: restart haproxy
  when: _full_os | bool
  service:
    name: rh-haproxy18-haproxy
    state: restarted

- name: restart firewall
  when: _full_os | bool
  service:
    name: iptables
    state: restarted

- name: restart rsyslog
  when: _full_os | bool
  service:
    name: rsyslog
    state: restarted
