---
- name: reload haproxy
  when: _full_os | bool
  service:
    name: haproxy
    state: reloaded

- name: restart haproxy
  when: _full_os | bool
  service:
    name: haproxy
    state: restarted

- name: restart rsyslog
  when: _full_os | bool
  service:
    name: rsyslog
    state: restarted
  notify: reload haproxy

- name: reboot
  debug:
    msg: REBOOT REQUIRED FOR SETTINGS TO TAKE
