---
_aegis_repl_resource: "{{
  irods_aegis_repl_resource if irods_aegis_repl_resource is defined else
  (irods_aegis_resource | default(_irods_default_repl_resource)) }}"
_aegis_resource: "{{ irods_aegis_resource | default(_irods_default_resource) }}"

_amqp_exchange: "{{ irods_amqp_exchange | default('irods') }}"
_amqp_host: "{{ irods_amqp_host | default(_irods_ies) }}"
_amqp_password: "{{ irods_amqp_password | default('guest') }}"
_amqp_port: "{{ irods_amqp_port | default(5672) }}"
_amqp_user: "{{ irods_amqp_user | default('guest') }}"
_amqp_vhost: "{{ irods_amqp_vhost | default('/') }}"

_avra_base_collection: "{{ avra_base_collection | default(None) }}"
_avra_manager: "{{ avra_manager | default(_irods_clerver_user) }}"
_avra_resource_hierarchy: "{{ avra_resource_hierarchy | default(_irods_resource_hierarchies[0]) }}"

_become_svc_acnt: "{{ become_svc_acnt | default(true) }}"

_bisque_irods_host: "{{ bisque_irods_host | default(_irods_ies) }}"
_bisque_password: "{{ bisque_password | default('admin') }}"
_bisque_projects: "{{ bisque_projects | default([]) }}"
_bisque_url: "{{ bisque_url | default(None) }}"
_bisque_user: "{{ bisque_user | default('admin') }}"

_build_dir: "{{ build_dir | default('/tmp') }}"

_canonical_hostname: "{{ canonical_hostname | default(_irods_ies) }}"
_canonical_irods_port: "{{ canonical_irods_port | default(_irods_zone_port) }}"

_captcn_owners: "{{ captcn_owners | default([]) }}"
_captcn_readers: "{{ captcn_readers | default([]) }}"
_captcn_writers: "{{ captcn_writers | default([]) }}"

_cereus_collections: "{{ cereus_collections | default([]) }}"
_cereus_resource_hierarchy: "{{
  cereus_resource_hierarchy | default(_irods_resource_hierarchies[0]) }}"

_check_routes_timeout: "{{ check_routes_timeout | default(3) }}"

_de_job_irods_user: "{{ de_job_irods_user | default(None) }}"

_firewall_chain: "{{ firewall_chain | default('INPUT') }}"

_irods_allowed_clients: "{{ irods_allowed_src | default('0.0.0.0/0') }}"
_irods_clerver_password: "{{ irods_clerver_password | default('rods') }}"
_irods_clerver_user: "{{ irods_clerver_user | default('rods') }}"
_irods_db_password: "{{ irods_db_password | default('testpassword') }}"
_irods_db_user: "{{ irods_db_user | default('irods') }}"
_irods_dbms_pg_hba: "{{ irods_dbms_pg_hba | default('/etc/postgresql/12/main/pg_hba.conf') }}"
_irods_dbms_pg_version: "{{ irods_dbms_pg_version | default('12') }}"
_irods_dbms_port: "{{ irods_dbms_port | default(5432) }}"
_irods_default_dir_mode: "{{ irods_default_dir_mode | default('0750') }}"
_irods_default_file_mode: "{{ irods_default_file_mode | default('0600') }}"
_irods_default_number_of_transfer_threads: "{{
  irods_default_number_of_transfer_threads | default(None) }}"
_irods_default_repl_resource: "{{ irods_default_repl_resource | default(_irods_default_resource) }}"
_irods_default_resource: "{{
  irods_default_resource | default(_irods_resource_hierarchies[0].name) }}"
_irods_default_vault: "{{ irods_default_vault | default(None) }}"
_irods_federation: "{{ irods_federation | default([]) }}"
_irods_host_aliases: "{{ irods_host_aliases | default([]) }}"
_irods_ies: "{{ irods_ies | default(groups['ies'][0]) }}"
_irods_max_num_re_procs: "{{ irods_max_num_re_procs | default(4) }}"
_irods_negotiation_key: "{{ irods_negotiation_key | default(None) }}"
_irods_other_host_entries: "{{ irods_other_host_entries | default([]) }}"
_irods_parallel_transfer_buffer_size: "{{ irods_parallel_transfer_buffer_size | default(None) }}"
_irods_publish_rs_image: "{{ irods_publish_rs_image | default(false) }}"
_irods_resource_hierarchies: '{{
  irods_resource_hierarchies
    if irods_resource_hierarchies is defined and irods_resource_hierarchies|length > 0 else
  [ { "name": "demoResc" } ] }}'
_irods_rs_image: "{{ irods_rs_image | default('ds-irods-rs-onbuild') }}"
_irods_server_port_range_end: "{{ irods_server_port_range_end | default(20199) }}"
_irods_server_port_range_start: "{{ irods_server_port_range_start | default(20000) }}"
_irods_server_control_plane_key: "{{ irods_server_control_plane_key | default(None) }}"
_irods_service_account_name: "{{ irods_service_account_name | default('irods') }}"
_irods_service_group_name: "{{ irods_service_group_name | default(_irods_service_account_name) }}"
_irods_storage_resources: "{{ irods_storage_resources | default([]) }}"
_irods_version: "{{ irods_version | default('4.1.11') }}"
_irods_zone_key: "{{ irods_zone_key | default(None) }}"
_irods_zone_name: "{{ irods_zone_name | default('tempZone') }}"

_pire_manager: "{{ pire_manager | default(None) }}"
_pire_resource_hierarchy: "{{ pire_resource_hierarchy | default(_irods_resource_hierarchies[0]) }}"

_proxy_irods_allowed_src: "{{ proxy_irods_allowed_src | default(_irods_allowed_clients) }}"
_proxy_irods_check_period: "{{ proxy_irods_check_period | default(2) }}"
_proxy_irods_extra_max_conn: "{{ proxy_irods_extra_max_conn | default(100) }}"
_proxy_irods_max_conn: "{{ proxy_irods_max_conn | default(200) }}"
_proxy_irods_vip_srcs: "{{ proxy_irods_vip_srcs | default([]) }}"
_proxy_queue_timeout: "{{ proxy_queue_timeout | default(120) }}"
_proxy_stats_allowed_src: "{{ proxy_stats_allowed_src | default('0.0.0.0/0') }}"
_proxy_stats_certificate: "{{ proxy_stats_certificate | default('/etc/haproxy/cert/stats.pem') }}"
_proxy_stats_port: "{{ proxy_stats_port | default(81) }}"
_proxy_stats_user: "{{ proxy_stats_user | default('haproxy-stats') }}"
_proxy_stats_password: "{{ proxy_stats_password | default('B1Gp4sSw0rD!!') }}"
_proxy_webdav_check_period: "{{ proxy_webdav_check_period | default(2) }}"

_report_email_addr: "{{ report_email_addr | default('root@localhost') }}"

_restart_irods: "{{ restart_irods | default(false) }}"

_sparcd_admin: "{{ sparcd_admin | default(None) }}"
_sparcd_base_collection: "{{
  sparcd_base_collection if sparcd_base_collection is defined else
  '/' + _irods_zone_name + '/home/' + _sparcd_admin + '/Sparcd/Collections' if _sparcd_admin else
  None }}"

_sernec_owners: "{{ sernec_owners if sernec_owners is defined else [] }}"
_sernec_readers: "{{ sernec_readers if sernec_readers is defined else [] }}"
_sernec_writers: "{{ sernec_writers if sernec_writers is defined else [] }}"

_single_threaded_resources: "{{ single_threaded_resources | default([]) }}"

_sysctl_kernel: "{{ sysctl_kernel | default([]) }}"

_terraref_base_collection: "{{ terraref_base_collection | default(None) }}"
_terraref_manager: "{{ terraref_manager | default(_irods_clerver_user) }}"
_terraref_resource_hierarchy: "{{
  terraref_resource_hierarchy | default(_irods_resource_hierarchies[0]) }}"

_webdav_allowed_src: "{{ webdav_allowed_src | default(['0.0.0.0/0']) }}"
_webdav_auth_name: "{{ webdav_auth_name | default('CyVerse') }}"
_webdav_cache_dir: "{{ webdav_cache_dir | default('/var/cache/varnish') }}"
_webdav_cache_size: "{{ webdav_cache_size | default(1000) }}"
_webdav_cache_max_file_size: "{{ webdav_cache_max_file_size | default(10) }}"
_webdav_cache_ttl_fraction: "{{ webdav_cache_ttl_fraction | default(0.1) }}"
_webdav_cache_max_ttl: "{{ webdav_cache_max_ttl | default(86400) }}"
_webdav_server_limit: "{{ webdav_server_limit | default(48) }}"
_webdav_threads_per_child: "{{ webdav_threads_per_child | default(4) }}"
_webdav_max_request_workers: "{{ webdav_max_request_workers | default(192) }}"
_webdav_access_limit: "{{ webdav_access_limit | default(120) }}"
_webdav_davrods_access_limit: "{{ webdav_davrods_access_limit | default(80) }}"
_webdav_tls_cert_file: "{{ webdav_tls_cert_file | default('/etc/ssl/certs/dummy.crt') }}"
_webdav_tls_chain_file: "{{ webdav_tls_chain_file | default('/etc/ssl/certs/dummy-chain.crt') }}"
_webdav_tls_key_file: "{{ webdav_tls_key_file | default('/etc/ssl/certs/dummy.key') }}"
_webdav_varnish_service_port: "{{ webdav_varnish_service_port | default(6081) }}"


# The following are internal constants

_irods_client_server_policy: CS_NEG_REFUSE
_irods_default_hash_scheme: MD5
_irods_server_control_plane_port: 1248
_irods_zone_port: 1247
