---
- import_tasks: _testing.yml

- name: configure | allowing proxy to listen on stats port
  when: ansible_selinux.status == 'enabled'
  seport:
    ports: "{{ haproxy_stats_port }}"
    proto: tcp
    setype: tor_port_t

- name: configure | enabling SELinux booleans for proxy
  when: ansible_selinux.status == 'enabled'
  seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true

- name: configure | configure rsyslog to listen on UDP socket
  blockinfile:
    path: /etc/rsyslog.conf
    insertafter: '# Provides UDP syslog reception'
    marker: "# {mark} DS MANAGED BLOCK (haproxy)"
    block: |
      $ModLoad imudp
      $UDPServerRun 514
      $UDPServerAddress 127.0.0.1
  notify:
    - restart rsyslog

- name: configure | place rsyslog config for HAProxy
  copy:
    src: rsyslog-haproxy.conf
    dest: /etc/rsyslog.d/haproxy.conf
    mode: u+r
  notify:
    - restart rsyslog

- name: configure | place logrotate config for HAProxy
  copy:
    src: logrotate-haproxy
    dest: /etc/logrotate.d/haproxy
    mode: u+r

- name: configure | add TLS certificates
  copy:
    dest: "{{ haproxy_stats_tls_crt }}"
    content: "{{ haproxy_stats_tls_crt_content }}"
    mode: a+r
  no_log: true
  when:
    - haproxy_stats_tls_crt | d(False)
    - haproxy_stats_tls_crt_content | d(False)
  notify:
    - reload haproxy

- name: configure | place VIP list
  template:
    src: templates/vip.lst.j2
    dest: /etc/haproxy/vip.lst
    owner: haproxy
    mode: u+r
  notify:
    - reload haproxy

- name: configure | place haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    mode: u=r
  notify:
    - reload haproxy
