---

- name: firewall | place nf_conntrack.conf
  copy:
    src: nf_conntrack.conf
    dest: /etc/modprobe.d/nf_conntrack.conf
    mode: u+r
  notify:
    - reboot

- name: firewall | allow access from stats client hosts to haproxy stats port 
  ufw:
    rule: allow
    src: "{{ item if item|ipaddr else lookup('dig', item) }}"
    port: "{{ haproxy_stats_port }}"
  with_items:
    - "{{ haproxy_stats_client_hosts }}"

- name: firewall | allow access from webdav client hosts to webdav port
  ufw:
    rule: allow
    src: "{{ item if item|ipaddr else lookup('dig', item) }}"
    port: "{{ haproxy_webdav_port }}"
  with_items:
    - "{{ haproxy_webdav_client_hosts }}"

- name: firewall | allow access from webdav client hosts to webdav tls port
  ufw:
    rule: allow
    src: "{{ item if item|ipaddr else lookup('dig', item) }}"
    port: "{{ haproxy_webdav_tls_port }}"
  with_items:
    - "{{ haproxy_webdav_client_hosts }}"

- name: firewall | allow access from irods client hosts to irods port
  ufw:
    rule: allow
    src: "{{ item if item|ipaddr else lookup('dig', item) }}"
    port: "{{ haproxy_irods_port }}"
  with_items:
    - "{{ haproxy_irods_client_hosts }}"

- name: firewall | allow access from irods client hosts to irods recon port
  ufw:
    rule: allow
    src: "{{ item if item|ipaddr else lookup('dig', item) }}"
    port: "{{ haproxy_irods_reconn_ports | regex_replace('-', ':') }}"
    protocol: tcp
  with_items:
    - "{{ haproxy_irods_client_hosts }}"

- name: firewall | allow access from webdav hosts to irods port
  ufw:
    rule: allow
    src: "{{ item if item|ipaddr else lookup('dig', item) }}"
    port: "{{ haproxy_irods_port }}"
  with_items:
    - "{{ haproxy_webdav_hosts }}"

- name: firewall | allow access from webdav hosts to irods recon port
  ufw:
    rule: allow
    src: "{{ item if item|ipaddr else lookup('dig', item) }}"
    port: "{{ haproxy_irods_reconn_ports | regex_replace('-', ':') }}"
    protocol: tcp
  with_items:
    - "{{ haproxy_webdav_hosts }}"


