---
- name: install | prepare if testing
  ansible.builtin.import_tasks: _testing.yml

- name: install | determine os
  when: ansible_distribution is not defined
  ansible.builtin.setup:
    gather_subset: pkg_mgr
    filter: ansible_pkg_mgr

- name: install | update apt cache
  when: ansible_pkg_mgr == 'apt'
  ansible.builtin.apt:
    update_cache: true

- name: install | install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: install | install socat
  ansible.builtin.package:
    name: socat
    state: present

- name: install | ensure haproxy starts on reboot
  ansible.builtin.service:
    name: haproxy
    enabled: true
  tags:
    - no_testing

- name: install | ensure nonlocal binding allowed
  ansible.builtin.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/haproxy.conf
    reload: true
    state: present
  notify:
    - restart haproxy
  tags:
    - no_testing

- name: install | ensure IP forwarding allowed
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/haproxy.conf
    reload: true
    state: present
  tags:
    - no_testing
