---
- import_tasks: _testing.yml

- name: install | install haproxy
  apt:
    name: haproxy
    state: present

- name: install | ensure haproxy starts on reboot
  service:
    name: haproxy
    enabled: true
  tags:
    - no_testing

- name: install | ensure nonlocal binding allowed
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/haproxy.conf
    reload: true
    state: present
  notify:
    - restart haproxy
  tags:
    - no_testing

- name: install | ensure IP forwarding allowed
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/haproxy.conf
    reload: true
    state: present
  tags:
    - no_testing
