---
pg_destroy_default_db_on_init: false

pg_downstream_nodes: []

pg_upstream_node: null

pg_conf_path: /etc/postgresql/12/main

pg_db: postgres
pg_db_path: /var/lib/postgresql/12/main  # changing this requires adjusting the systemctl file.

pg_hba_insertafter: '# ----------------------------------'
pg_hba_users: []

# configuration defaults
pg_checkpoint_completion_target: 0.5
pg_checkpoint_timeout: 5min

pg_effective_cache_size: 4GB

pg_hot_standby_feedback: 'off'

pg_extra_listen_addresses: []
pg_listen_port: 5432

pg_log_line_prefix: '%m [%p] %q%u@%d '
pg_log_min_duration_statement: -1

pg_max_connections: 100

pg_wal_keep_segments: 0
pg_max_wal_senders: 10
pg_min_wal_size: 80MB
pg_max_wal_size: 1GB

pg_random_page_cost: 4.0

pg_shared_buffers: 128MB

pg_standard_conforming_strings: 'on'

pg_work_mem: 4MB
pg_maintenance_work_mem: 64MB
