---
- name: Set up HAProxy
  hosts: proxy
  become: true
  roles:
    - role: haproxy
      vars:
        haproxy_default_max_conn: 500
        haproxy_default_queue_timeout: 10m

        haproxy_stats_port: 81
        haproxy_stats_tls_crt: /etc/haproxy/certs/cyverse_pem.pem
        haproxy_stats_auth:
          username: ds
          password: tokyo_bestbuy
          realm: CyVerse-DS-Dev
        haproxy_stats_source_hosts:
          - 128.196.38.31
          - 150.135.0.0/16

        haproxy_irods_port: 1247
        haproxy_irods_reconn_first_port: 20000
        haproxy_irods_reconn_last_port: 20099
        haproxy_irods_backend_host: 128.196.65.26
        haproxy_irods_backend_port: 1247
        haproxy_irods_backend_reconn_first_port: 20000
        haproxy_irods_backend_reconn_last_port: 20099
        haproxy_irods_single_max_conn: 300
        haproxy_irods_extra_max_conn: 100
        haproxy_irods_source_hosts:
          - 128.196.0.0/16
        haproxy_irods_vip_source_hosts:
          - 128.196.38.0/24

        haproxy_webdav_port: 80
        haproxy_webdav_tls_port: 443
        haproxy_webdav_backend_hosts:
          - 128.196.65.156
          - 128.196.65.157
        haproxy_webdav_source_hosts:
          - 128.196.0.0/16
