---
- name: install maintainer keys
  hosts: all:!localhost
  tasks:
    - name: install key
      ansible.posix.authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ item }}"
      with_items: "{{ _maintainer_keys }}"
