---
- name: install ansible core facts requirement
  hosts: all:!unmanaged_systems:!localhost
  become: true
  gather_facts: false
  tasks:
    - import_tasks: tasks/set_python.yml

    - name: install dmidecode support
      package:
        name: dmidecode
        state: present
        use: "{{ _package_manager }}"


- name: install required packages for ansible
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tasks:
    - name: update apt cache on Ubuntu machines
      when: ansible_distribution == 'Ubuntu'
      apt:
        update_cache: true
      tags:
        - non_idempotent

    - name: install EPEL repository on CentOS machines
      when: ansible_distribution == 'CentOS'
      package:
        name: epel-release
        state: present

    - name: install yum-plugin-versionlock on CentOS machines
      when: ansible_distribution == 'CentOS'
      package:
        name: yum-plugin-versionlock
        state: present

    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ 'iproute2' if ansible_distribution == 'Ubuntu' else 'iproute' }}"
        - jq
        - "{{ 'libselinux-python' if ansible_distribution == 'CentOS' else
              'python3-selinux' if ansible_distribution == 'Ubuntu' else
              'python-selinux' }}"
        - "{{ 'python3-dns' if ansible_distribution == 'Ubuntu' else 'python-dns' }}"
        - "{{ 'python3-pip' 
                if ansible_distribution == 'CentOS' or ansible_distribution == 'Ubuntu' else
              'python-pip' }}"
        - "{{ 'python3-requests' if ansible_distribution == 'Ubuntu' else 'python-requests' }}"
        - "{{ 'python3-virtualenv' if ansible_distribution == 'Ubuntu' else 'python-virtualenv' }}"
