---
- name: initialize iptables
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tasks:
    - import_tasks: tasks/set_python.yml  
        
    - name: install iptables package
      package:
        name: "{{ 'iptables-services' if ansible_distribution == 'CentOS' else 'iptables' }}"
        state: present
