---
- name: initialize iptables
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tasks:
    - name: install iptables package
      package:
        name: >-
          {{ 'iptables-persistent' if ansible_distribution == 'Ubuntu' else 'iptables-services' }}
        state: present
