---
- name: reboot servers
  hosts: all:!unmanaged_systems:!localhost
  become: true
  vars:
    _port: "{{ ansible_port | default(22) }}"
  tasks:
    - when: _rebootable
      block:
        - name: reboot
          shell: |
            sleep 1
            reboot
          async: 1000000000
          poll: 0
          ignore_errors: true

        - name: wait for server to stop
          become: false
          local_action: wait_for host={{ inventory_hostname }} port={{ _port }} state=stopped

        - name: verify server up
          become: false
          local_action: wait_for host={{ inventory_hostname }} port={{ _port }} state=started
  tags:
    - no_testing
