---
- name: reboot servers
  hosts: all:!unmanaged_systems:!localhost
  become: true
  vars:
    _port: "{{ ansible_port | default(22) }}"
  tasks:
    - when: _rebootable
      block:
        - name: reboot
          shell: |
            sleep 1
            reboot
          async: 1000000000
          poll: 0
          ignore_errors: true

        - name: wait for server to stop
          wait_for:
            host: "{{ inventory_hostname }}"
            port: "{{ _port }}"
            state: stopped
          delegate_to: localhost
          become: false

        - name: verify server up
          wait_for:
            host: "{{ inventory_hostname }}"
            port: "{{ _port }}"
            state: started
          delegate_to: localhost
          become: false
  tags:
    - no_testing
