---
- name: ensure correct timezone
  hosts: all:!unmanaged_systems:!localhost
  become: true
  collections:
    - community.general
  tags:
    - no_testing
  tasks:
    - name: make Mountain Standard Time
      timezone:
        name: America/Phoenix
      notify:
        - restart crond

  handlers:
    - name: restart crond
      service:
        name: crond
        state: restarted
