---
- name: upgrade system packages
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tasks:
    - name: update apt cache on Ubuntu machines
      when: ansible_distribution == 'Ubuntu'
      apt:
        update_cache: true
      tags:
        - non_idempotent

    - name: upgrade system packages
      when: _rebootable | bool
      package:
        name: '*'
        state: latest
