---
- name: block client access
  hosts: proxy
  become: true
  tasks:
    - import_role:
        name: haproxy
        tasks_from: firewall
      vars:
        haproxy_irods_host: "{{ groups['irods_catalog'][0] }}"
        haproxy_irods_reconn_ports: "{{ proxy_irods_reconn_ports }}"
        haproxy_irods_client_hosts: "{{ groups['webdav'] }}"
        haproxy_webdav_hosts: "{{ groups['webdav'] }}"
        haproxy_webdav_client_hosts: []
