---
- name: terminate client connections
  hosts: proxy
  become: true
  collections:
    - community.general
  tags:
    - no_testing
  tasks:
    - name: terminate SFTP connections
      haproxy:
        backend: sftp
        host: sftp
        state: disabled
        shutdown_sessions: true
        fail_on_not_found: true

    - name: terminate WebDAV connections
      haproxy:
        backend: webdav
        host: dav
        state: disabled
        shutdown_sessions: true
        fail_on_not_found: true

    - name: terminate iRODS connections
      haproxy:
        backend: irods_direct
        host: irods
        state: disabled
        shutdown_sessions: true
        fail_on_not_found: true
