---
- name: terminate client connections
  hosts: proxy
  become: true
  collections:
    - community.general
  tags:
    - no_testing
  tasks:
    - name: terminate WebDAV connections
      haproxy:
        host: "{{ inventory_hostname }}"
        backend: webdav
        state: disabled
        shutdown_sessions: true

    - name: terminate iRODS connections
      haproxy:
        host: "{{ inventory_hostname }}"
        backend: irods_direct
        state: disabled
        shutdown_sessions:: true
