---
- name: terminate client connections
  hosts: proxy
  become: true
  tasks:
    - name: disable testing
      set_fact:
        _full_os: true
      tags:
        - no_testing

    - name: reject all incoming packets
      blockinfile:
        path: /etc/sysconfig/iptables
        insertbefore: '-A INPUT -m state --state .*ESTABLISHED.* -j ACCEPT'
        marker: "# {mark} DS MANAGED BLOCK (haproxy reject)"
        block: |
          {% for w in groups['webdav'] %}
          {%   set addr = w if w|ansible.utils.ipaddr else lookup('dig', w) %}
          -A INPUT -m state --state UNTRACKED -s {{ addr }} -j ACCEPT
          {% endfor %}
          -A INPUT -p tcp --dport 80 -j REJECT
          -A INPUT -p tcp --dport 443 -j REJECT
          -A INPUT -p tcp --dport 1247 -j REJECT
          -A INPUT -p tcp --dport {{ proxy_irods_reconn_ports | regex_replace('-', ':') }} -j REJECT
        state: present
      notify:
        - reload firewall rules

  handlers:
    - name: reload firewall rules
      when: _full_os | default(false)
      service:
        name: iptables
        state: restarted
