---
- name: terminate client connections
  hosts: proxy
  become: true
  tasks:
    - name: disable testing
      set_fact:
        _full_os: true
      tags:
        - no_testing

    - name: reject all incoming packets
      blockinfile:
        path: /etc/sysconfig/iptables
        insertafter: ':OUTPUT ACCEPT [0:0]'
        marker: "# {mark} DS MANAGED BLOCK (haproxy reject)"
        block: |
          -A INPUT -p tcp --dport 80 -j REJECT
          -A INPUT -p tcp --dport 443 -j REJECT
          -A INPUT -p tcp --dport 1247 -j REJECT
          -A INPUT -p tcp --dport {{ proxy_irods_reconn_ports }} -j REJECT
        state: present
      notify:
        - reload firewall rules

  handlers:
    - name: reload firewall rules
      when: _full_os | default(false)
      service:
        name: iptables
        state: restarted
