---
- name: restore all client access
  hosts: proxy
  become: true
  collections:
    - community.general
  tasks:
    - name: disable testing
      set_fact:
        _full_os: true
      tags:
        - no_testing

    - name: enable iRODS access
      haproxy:
        host: "{{ inventory_hostname }}"
        backend: irods_direct
        state: enabled
        wait: true
      tags:
        - no_testing

    - name: enable WebDAV access
      haproxy:
        host: "{{ inventory_hostname }}"
        backend: webdav
        state: enabled
        wait: true
      tags:
        - no_testing

    - import_role:
        name: haproxy
        tasks_from: firewall
      vars:
        haproxy_irods_host: "{{ groups['irods_catalog'][0] }}"
        haproxy_irods_reconn_ports: "{{ proxy_irods_reconn_ports }}"
        haproxy_webdav_hosts: "{{ groups['webdav'] }}"
