---
- name: restore all client access
  hosts: proxy
  become: true
  collections:
    - community.general
  tags:
    - no_testing
  tasks:
    - name: disable testing
      set_fact:
        _full_os: true

    - name: enable iRODS access
      haproxy:
        backend: irods_direct
        host: irods
        state: enabled
        fail_on_not_found: true

    - name: enable WebDAV access
      haproxy:
        backend: webdav
        host: dav
        state: enabled
        fail_on_not_found: true

    - name: enable SFTP access
      haproxy:
        backend: sftp
        host: sftp
        state: enabled
        fail_on_not_found: true
