---
- name: restore all client access
  hosts: proxy
  become: true
  tasks:
    - import_role:
        name: haproxy
        tasks_from: firewall
      vars:
        haproxy_irods_host: "{{ groups['ies'][0] }}"
        haproxy_irods_reconn_ports: "{{ proxy_irods_reconn_ports }}"
        haproxy_webdav_hosts: "{{ groups['webdav'] }}"
