---
- name: restore internal client access
  hosts: proxy
  become: true
  collections:
    - community.general
  tasks:
    - name: disable testing
      set_fact:
        _full_os: true
      tags:
        - no_testing

    - name: enable iRODS access
      haproxy:
        backend: irods_direct
        host: irods
        state: enabled
        wait: true
        fail_on_not_found: true
      tags:
        - no_testing

    - name: enable WebDAV access
      haproxy:
        backend: webdav
        host: dav
        state: enabled
        wait: true
        fail_on_not_found: true
      tags:
        - no_testing

    - import_role:
        name: haproxy
        tasks_from: firewall
      vars:
        haproxy_irods_host: "{{ groups['irods_catalog'][0] }}"
        haproxy_irods_reconn_ports: "{{ proxy_irods_reconn_ports }}"
        haproxy_irods_client_hosts: "{{ proxy_internal_client_hosts | union(groups['webdav']) }}"
        haproxy_webdav_hosts: "{{ groups['webdav'] }}"
        haproxy_webdav_client_hosts: "{{ proxy_internal_client_hosts }}"
