---
- name: create AMQP exchange
  hosts: ies
  become: true
  run_once: true
  gather_facts: false
  tasks:
    - import_role:
        name: cyverse.rabbitmq_vhost
      vars:
        rabbitmq_mgmt_port: "{{ _amqp_mgmt_port }}"
        rabbitmq_admin_user: "{{ _amqp_user }}"
        rabbitmq_admin_password: "{{ _amqp_password }}"
        rabbitmq_vhost_name: "{{ _amqp_vhost }}"
        rabbitmq_vhost_users:
          - name: "{{ _amqp_user }}"
            configure_priv: .*
            read_priv: .*
            write_priv: .*
        rabbitmq_vhost_exchanges:
          - name: "{{ _amqp_exchange }}"
            type: topic
      delegate_to: "{{ _amqp_host }}"
      delegate_facts: true
  tags:
    - no_testing
