---
- import_playbook: mk_storage_resources.yml


- name: Configure IES for Avra
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - when: _avra_base_collection != ''
      block:
        - name: create avra resource
          irods_resource_hierarchy:
            hierarchy: "{{ _avra_resource_hierarchy }}"

        - name: create project collection
          delegate_to: localhost
          become: false
          irods_collection:
            path: "{{ _avra_base_collection }}"
            parents: true
            state: present
            host: "{{ groups['ies'][0] }}"
            port: "{{ _irods_zone_port }}"
            admin_user: "{{ _irods_clerver_user }}"
            admin_password: "{{ _irods_clerver_password }}"
            zone: "{{ _irods_zone_name }}"

        - name: assign owner to project collection
          irods_permission:
            subject: "{{ _avra_manager }}"
            permission: own
            object: "{{ _avra_base_collection }}"
