---
- name: prepare for bisque_paths
  hosts: ies
  become: true
  tasks:
    - name: ensure /var/log/bisque exists
      file:
        path: /var/log/bisque
        state: directory
        owner: "{{ _irods_service_account_name }}"
        group: "{{ _irods_service_group_name }}"
        mode: u=rwx


- name: configure bisque client
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: install bisque_paths.py
      get_url:
        validate_certs: no
        url: https://gitlab.cyverse.org/ds/bisque_support/raw/master/bisque_paths/bisque_paths.py
        dest: /var/lib/irods/iRODS/server/bin/cmd
        mode: u+wx

    - name: place .bisque
      when: _bisque_url is defined
      template:
        src: templates/bisque.j2
        dest: "{{ ansible_env.HOME }}/.bisque"
        mode: u=r
