---
- name: allow IES to talk to DBMS
  hosts: dbms
  become: true
  tasks:
    - name: enable notifications when not testing
      set_fact:
        notifications_enabled: true
      tags:
        - no_testing

    - name: allow IES to communicate with Postgres DBMS
      blockinfile:
        path: "{{ _irods_dbms_pg_hba }}"
        marker: "# {mark} DS IRODS MANAGED BLOCK"
        block: |
          {% for i in groups['ies'] %}
          {%   set addr = i if i|ipaddr else lookup('dig', i) %}
          {{   '%-7s %-15s %-15s %-23s %s'
                 | format('host', 'ICAT', hostvars[i]._irods_db_user, addr ~ '/32', 'md5') }}
          {% endfor %}
      notify:
        - reload postgresql

  handlers:
    - name: reload postgresql
      when: notifications_enabled | default(false)
      service:
        name: postgresql
        state: reloaded


- import_playbook: provision.yml


- name: provision additional for IES
  hosts: ies
  become: true
  vars:
    # NB: The rpm and yum bindings for the package module require Python 2 in
    #     Ansible 2.9.6
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: configure linux kernel
      sysctl:
        name: kernel.{{ item.name }}
        value: "{{ item.value }}"
      with_items: "{{ _sysctl_kernel }}"
      tags:
        - no_testing

    - name: verify PostgreSQL client version is 9.3 or 12
      when: _irods_dbms_pg_version != '9.3' and _irods_dbms_pg_version != '12'
      fail:
        msg: Only PostgreSQL client versions 9.3 and 12 are supported

    - name: ensure PostgreSQL 9.3 clients are installed
      when: _irods_dbms_pg_version == '9.3'
      yum:
        name:
          - https://download.postgresql.org/pub/repos/yum/9.3/redhat/rhel-7-x86_64/postgresql93-libs-9.3.25-1PGDG.rhel7.x86_64.rpm
          - https://download.postgresql.org/pub/repos/yum/9.3/redhat/rhel-7-x86_64/postgresql93-9.3.25-1PGDG.rhel7.x86_64.rpm
          - https://download.postgresql.org/pub/repos/yum/9.3/redhat/rhel-7-x86_64/postgresql93-odbc-10.03.0000-1PGDG.rhel7.x86_64.rpm

    - when: _irods_dbms_pg_version == '12'
      block:
        - name: ensure PostgreSQL 12 repo is installed
          yum:
            name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

        - name: ensure PostgreSQL 12 clients are installed
          package:
            name:
              - postgresql12
              - postgresql12-odbc
            state: present

        - name: add postgres 12 clients to path
          copy:
            src: "{{ item }}"
            dest: /etc/profile.d
          with_fileglob:
            - "files/profile.d/*"

    - name: ensure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - mailx
        - parallel

    - name: ensure pika installed
      pip:
        name: pika<1.2
        state: present

    - import_tasks: tasks/install_ies_pkgs.yml

    - import_tasks: tasks/install_plugins.yml


- import_playbook: cfg_irods.yml


- name: start iRODS on IES
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  gather_facts: false
  tasks:
    - name: start iRODS
      irods_ctl:

    - name: authenticate clerver
      irods_clerver_auth:
        ies: "{{ inventory_hostname }}"
        password: "{{ _irods_clerver_password }}"


- import_playbook: irods_runtime_init.yml


- import_playbook: bisque_usage.yml
