---
- name: create ICAT DB
  hosts: dbms_primary
  become: true
  become_user: postgres
  run_once: true
  roles:
    - role: postgresql_db
      vars:
        postgresql_db_dbms_port: "{{ _irods_dbms_port }}"
        postgresql_db_name: ICAT
        postgresql_db_admin_user: "{{ _irods_db_user }}"
        postgresql_db_admin_password: "{{ _irods_db_password }}"
