---
- name: allow IES to talk to DBMS
  hosts: dbms
  become: true
  vars:
    __icat_dbms_dir: /etc/postgresql/12/main
  tasks:
    - name: enable notifications when not testing
      set_fact:
        notifications_enabled: true
      tags:
        - no_testing

    - name: allow IES to communicate with Postgres DBMS
      blockinfile:
        path: "{{ __icat_dbms_dir }}/pg_hba.conf"
        insertafter: '# IPv4 local connections:'
        marker: "# {mark} DS MANAGED BLOCK"
        block: |
          {% for i in groups['ies'] %}
          {%   set addr = i if i|ipaddr else lookup('dig', i) %}
          {{ '%-8s %-15s %-15s %-23s %s' | format('host', 'ICAT', _dbms_username, addr ~ '/32', 'md5')
            }}
          {% endfor %}
      notify:
        - reload postgresql

  handlers:
    - name: restart firewall
      when: notifications_enabled | default(false)
      service:
        name: iptables
        state: restarted

    - name: reload postgresql
      when: notifications_enabled | default(false)
      service:
        name: postgresql-9.3
        state: reloaded


- import_playbook: provision.yml


- name: provision additional for IES
  hosts: ies
  become: true
  tasks:
    - name: configure linux kernel
      sysctl:
        name: kernel.{{ item.name }}
        value: "{{ item.value }}"
      with_items: "{{ _sysctl_kernel }}"
      tags:
        - no_testing

    - name: ensure PostgreSQL 12 repo installed
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

    - name: ensure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - mailx
        - parallel
        - postgresql12
#        - postgresql12-odbc
# XXX postgresql12-odbc package is currently unsigned, causing package to fail
#     to install it. Once it is signed again, revert this change.
    - yum:
        name: postgresql12-odbc
        disable_gpg_check: yes

    - name: ensure PostgreSQL 9 clients are removed
      package:
        name:
          - postgresql93
          - postgresql93-libs
          - postgresql93-odbc
        state: absent
      notify: stop ies

    - name: ensure pika installed
      pip:
        name: pika
        state: present

    - import_tasks: tasks/install_ies_pkgs.yml

    - import_tasks: tasks/install_plugins.yml

  handlers:
    - name: stop ies
      become: "{{ _become_svc_acnt }}"
      become_user: "{{ _irods_service_account_name }}"
      irods_ctl:
        state: stopped

- import_playbook: cfg_irods.yml


- name: start iRODS on IES
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  gather_facts: false
  tasks:
    - name: start iRODS
      irods_ctl:

    - name: authenticate clerver
      irods_clerver_auth:
        ies: "{{ inventory_hostname }}"
        password: "{{ _irods_clerver_password }}"


- import_playbook: irods_runtime_init.yml


- import_playbook: bisque_usage.yml
