---
- import_playbook: provision.yml


- name: install resource server package
  hosts: irods_resource:!irods_catalog:!unmanaged_systems
  become: true
  tasks:
    - import_tasks: tasks/install_resource_pkg.yml

    - import_tasks: tasks/install_plugins.yml


- import_playbook: cfg_irods.yml


- name: ensure catalog service providers are started
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: start iRODS
      irods_ctl:


- name: bootstrap iRODS start
  hosts: irods_resource:!irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  tasks:
    - name: create clerver user
      delegate_to: localhost
      become: false
      irods_user:
        name: "{{ _irods_clerver_user }}"
        type: rodsadmin
        state: present
        password: "{{ _irods_clerver_password }}"
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: ensure clerver user is in group rodsadmin
      delegate_to: localhost
      become: false
      irods_group_member:
        group: rodsadmin
        users:
          - "{{ _irods_clerver_user }}"
        state: present
        host: "{{ groups['irods_catalog'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: initialize resource server connection to catalog service providers
      irods_clerver_auth:
        ies: "{{ groups['irods_catalog'][0] }}"
        password: "{{ _irods_clerver_password }}"

    - name: start iRODS
      irods_ctl:


- import_playbook: mk_storage_resources.yml
