---
- name: run-time initialization
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  run_once: true
  tasks:
    - name: ensure service user type exists
      irods_user_type:
        type: ds-service
        description: a Data Store service

    - name: ensure public group's home is correct
      irods_move:
        source: /{{ _irods_zone_name }}/home/public
        destination: /{{ _irods_zone_name }}/home/shared

    - name: ensure CyVerse curated collection base collection exists
      become: false
      delegate_to: localhost
      irods_collection:
        path: /{{ _irods_zone_name }}/home/shared/commons_repo/curated
        parents: true
        state: present
        host: "{{ groups['ies'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: force initialize perms when not testing
      set_fact:
        init_rodsadmin_perms_default: false
      tags:
        - no_testing

    - name: initialize perms
      when: |
        (init_rodsadmin_perms is not defined and (init_rodsadmin_perms_default | default(true)))
        or init_rodsadmin_perms
      script: scripts/init-rodsadmin-perms.sh '{{
        groups['dbms'][0] }}' '{{ _dbms_port }}' '{{ _dbms_username }}' '{{ _irods_zone_name }}'
      register: response
      changed_when: response.stdout == 'true'

    - name: ensure anonymous user exists
      delegate_to: localhost
      become: false
      irods_user:
        name: anonymous
        password: ''
        state: present
        host: "{{ groups['ies'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: ensure anonymous user has read access to required collections
      irods_permission:
        subject: anonymous
        permission: read
        object: "{{ item }}"
      with_items:
        - /{{ _irods_zone_name }}
        - /{{ _irods_zone_name }}/home
        - /{{ _irods_zone_name }}/home/shared
        - /{{ _irods_zone_name }}/home/shared/commons_repo/curated

    - name: start quota usage computation
      command: irule ipc_rescheduleQuotaUsageUpdate null ruleExecOut
      register: results
      changed_when: results.stdout == 'scheduled quota usage updates'

    - name: start trash removal
      command: irule ipc_rescheduleTrashRemoval null ruleExecOut
      register: results
      changed_when: results.stdout == 'scheduled trash removal'
