---
- name: enable restarting of iRODS
  hosts: irods
  tasks:
    - set_fact:
        restart_irods: true


- name: configure AMQP broker
  hosts: rabbitmq[0]
  become: true
  roles:
    - role: cyverse.rabbitmq-vhost
      rabbitmq_vhost_name: "{{ _rabbitmq_vhost }}"
      rabbitmq_vhost_users:
        - name: "{{ _rabbitmq_user }}"
          configure_priv: .*
          write_priv: .*
          read_priv: .*


- import_playbook: provision.yml


- import_playbook: cfg_irods.yml


- name: start iRODS on IES
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  gather_facts: false
  tasks:
    - name: start iRODS
      irods_ctl:


- name: start iRODS on resource servers
  hosts: rs:!ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  gather_facts: false
  tasks:
    - name: start iRODS
      irods_ctl:


- import_playbook: irods_runtime_init.yml


- import_playbook: bisque_usage.yml


- import_playbook: de_usage.yml
