---
- name: create vaults
  hosts: irods_resource:!unmanaged_systems
  become: true
  tasks:
    - name: create vault directory
      file:
        path: "{{ item.vault }}"
        follow: true
        owner: "{{ _irods_service_account_name }}"
        group: "{{ _irods_service_group_name }}"
        mode: 'u=rwx'
        state: directory
      with_items: "{{ _irods_storage_resources }}"


- name: create storage resources
  hosts: irods_resource
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: define storage resource
      irods_unixfilesystem_resource:
        name: "{{ item.name }}"
        location: "{{ inventory_hostname }}"
        vault: "{{ item.vault }}"
        context: "{{ item.context }}"
        status: down
        init_free_space: true
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

      with_items: "{{ _irods_storage_resources }}"
