---
- import_playbook: mk_storage_resources.yml


- name: Configure IES for PIRE
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - irods_resource_hierarchy:
        hierarchy: "{{ _pire_resource_hierarchy }}"

    - name: create project collection
      delegate_to: localhost
      become: false
      irods_collection:
        path: /{{ _irods_zone_name }}/home/shared/bhpire
        parents: true
        host: "{{ groups['ies'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"

    - name: create public collection
      delegate_to: localhost
      become: false
      irods_collection:
        path: /{{ _irods_zone_name }}/home/shared/eht
        parents: true
        state: present
        host: "{{ groups['ies'][0] }}"
        port: "{{ _irods_zone_port }}"
        admin_user: "{{ _irods_clerver_user }}"
        admin_password: "{{ _irods_clerver_password }}"
        zone: "{{ _irods_zone_name }}"
