---
- name: stop the webdav services
  hosts: webdav
  tasks:
    - name: stop apache
      service:
        name: httpd
        state: stopped

    - name: stop varnish
      service:
        name: varnish
        state: stoppped
  tags:
    - no_testing
