---
- name: stop iRODS resource servers
  hosts: irods_resource:!irods_catalog
  tasks:
    - import_tasks: tasks/stop_irods.yml


- name: stop catalog service providers
  hosts: irods_catalog
  tasks:
    - import_tasks: tasks/stop_irods.yml
