---
- name: remove housekeeping rules
  hosts: ies
  run_once: true
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: remove periodic rules
      shell: |
        if ! ids="$(\
          iquest --no-page '%s' \
            "select RULE_EXEC_ID 
              where RULE_EXEC_USER_NAME = '{{ _irods_admin_username }}' 
              and RULE_EXEC_FREQUENCY like '% REPEAT FOR EVER'" )"
        then
          exit 1
        fi
        if ! [[ "$ids" =~ ^CAT_NO_ROWS_FOUND: ]]; then
          xargs iqdel <<< "$ids" > /dev/null
          echo changed
        fi
      register: response
      changed_when: response.stdout == 'changed'


- import_playbook: stop_all.yml
