---
- name: clean up - general
  hosts: irods
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: remove backups of config files
      shell: |
        set -o errexit
        if ! res="$(\
          rm --force --verbose \
            /etc/irods/*.prev.* /var/lib/irods/.irods/irods_environment.json.prev.* )"
        then
          exit 1
        fi
        if [[ -n "$res" ]]; then
          echo changed
        fi
      register: response
      changed_when: response.stdout == 'changed'

    - name: removed vestigal folders
      file:
        path: /var/lib/irods/{{ item }}
        state: absent
      with_items:
        - iRODS
        - plugins

    - name: remove VERSION.json.previous
      file:
        path: /var/lib/irods/VERSION.json.previous
        state: absent


- name: clean up - catalog provider specific
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  gather_facts: false
  tasks:
    - name: remove postgres section from .odbc.ini
      replace:
        path: /var/lib/irods/.odbc.ini
        regexp: '\[postgres\][^\[]*'

    - name: remove old DBMS related files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/irods/.pgpass
        - /var/lib/irods/.psql_history
        - /etc/irods/database_config.json

    - name: removed files generated by upgrade
      file:
        path: /var/lib/irods/{{ item }}
        state: absent
      with_items:
        - convert-to-db-schema-6-part-1.sql
        - convert-to-db-schema-6-part-2.sql
        - pre-rs-script.sh
        - post-rs-script.sh
        - pre-rs-script-run
        - post-rs-script-run
