---
- name: upgrade WebDAV services
  hosts: webdav
  become: true
  tasks:
    - name: remove iCommands
      package:
        name: irods-icommands
        state: absent

    - name: install iRODS package repository signing key
      rpm_key:
        key: https://packages.irods.org/irods-signing-key.asc

    - name: install iRODS repository
      get_url:
        url: https://packages.irods.org/renci-irods.yum.repo
        dest: /etc/yum.repos.d/renci-irods.yum.repo

    - name: upgrade davrods
      yum:
        name: https://github.com/UtrechtUniversity/davrods/releases/download/4.2.8_1.5.0/davrods-4.2.8_1.5.0-1.rpm
        state: present

    - name: remove newly installed irods_environment.json
      file:
        path: /etc/httpd/irods/irods_environment.json.rpmnew
        state: absent
