---
- name: stop the webdav services
  hosts: webdav
  become: true
  tasks:
    - name: stop apache
      service:
        name: httpd
        state: stopped

    - name: stop varnish
      service:
        name: varnish
        state: stopped
  tags:
    - no_testing
