---
- name: start the webdav services
  hosts: webdav
  become: true
  tags:
    - no_testing
  tasks:
    - name: start varnish
      service:
        name: varnish
        state: started
        enabled: true

    - name: start varnishncsa
      service:
        name: varnishncsa
        state: started
        enabled: true

    - name: start apache
      service:
        name: httpd
        state: started
        enabled: true

    - name: start purgeman
      service:
        name: purgeman
        state: started
        enabled: true