---
- name: stop the webdav services
  hosts: webdav
  become: true
  tags:
    - no_testing
  tasks:
    - name: stop apache
      service:
        name: httpd
        state: stopped
        enabled: false

    - name: stop purgeman
      service:
        name: purgeman
        state: stopped
        enabled: false

    - name: stop varnishncsa
      service:
        name: varnishncsa
        state: stopped
        enabled: false

    - name: stop varnish
      service:
        name: varnish
        state: stopped
        enabled: false