---
- name: reboot
  debug:
    msg: REBOOT REQUIRED FOR SETTINGS TO TAKE
    
- name: restart postgres
  service:
    name: postgresql
    state: restarted

- name: reload postgres
  service:
    name: postgresql
    state: reloaded
