---
- name: Verify that an admin password was provided
  assert:
    that:
      - postgresql_db_admin_password is defined

- name: Ensure database exists {{ postgresql_db_name }}
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db_name }}"
    port: "{{ postgresql_db_dbms_port }}"
    login_password: "{{ postgresql_db_admin_password }}"

- name: Ensure database admin user exists {{ postgresql_db_name }}
  community.postgresql.postgresql_user:
    name: "{{ postgresql_db_admin_user }}"
    password: "{{ postgresql_db_admin_password }}"
    db: "{{ postgresql_db_name }}"
    priv: all
    port: "{{ postgresql_db_dbms_port }}"
    login_password: "{{ postgresql_db_admin_password }}"
  # no_log: true
