---
- name: verify that an admin password was provided
  assert:
    that:
      - postgresql_db_admin_password is defined

- name: ensure {{ postgresql_db_name }} database exists
  postgresql_db:
    name: "{{ postgresql_db_name }}"
    port: "{{ postgresql_db_dbms_port }}"

- name: ensure {{ postgresql_db_name }} database admin user exists
  postgresql_user:
    name: "{{ postgresql_db_admin_user }}"
    password: "{{ postgresql_db_admin_password }}"
    db: "{{ postgresql_db_name }}"
    priv: all
    port: "{{ postgresql_db_dbms_port }}"
  no_log: true
