---
# Configure the Data Store for a given Cereus project.
#
# Variables:
#  project  the cereus_project object holding the configuration.

- name: create project collection
  delegate_to: localhost
  become: false
  irods_collection:
    path: "{{ project.base_collection }}"
    parents: true
    state: present
    host: "{{ groups['ies'][0] }}"
    port: "{{ _irods_zone_port }}"
    zone: "{{ _irods_zone_name }}"
    admin_user: "{{ _irods_clerver_user }}"
    admin_password: "{{ _irods_clerver_password }}"

- name: assign owner to project collection
  delegate_to: localhost
  become: false
  irods_permission:
    subject: "{{ project.owner }}"
    permission: own
    object: "{{ project.base_collection }}"
    host: "{{ groups['ies'][0] }}"
    port: "{{ _irods_zone_port }}"
    zone: "{{ _irods_zone_name }}"
    admin_user: "{{ _irods_clerver_user }}"
    admin_password: "{{ _irods_clerver_password }}"

- name: assign collection to Cereus resource
  delegate_to: localhost
  become: false
  irods_avu:
    entity_type: resource
    entity_name: "{{ _cereus_resource_hierarchy.name }}"
    attribute: ipc::hosted-collection
    value: "{{ project.base_collection }}"
    units: preferred
    host: "{{ groups['ies'][0] }}"
    port: "{{ _irods_zone_port }}"
    zone: "{{ _irods_zone_name }}"
    username: "{{ _irods_clerver_user }}"
    password: "{{ _irods_clerver_password }}"
