---
- name: ensure netcdf plugins not installed
  package:
    name:
      - irods-icommands-netcdf
      - irods-microservice-plugin-netcdf
      - irods-api-plugin-netcdf
    state: absent

- name: ensure netcdf rpms removed
  file:
    path: /root/{{ item }}-1.0-centos{{ ansible_distribution_major_version }}.rpm
    state: absent
  with_items:
    - irods-icommands-netcdf
    - irods-microservice-plugin-netcdf
    - irods-api-plugin-netcdf

- name: install NetCDF plugins
  yum:
    name:
      - http://people.renci.org/~dmoore/irods_netcdf/packages_2021_03_24/irods-netcdf-client_modules-4.2.8.0-centos-7-x86_64.rpm
      - http://people.renci.org/~dmoore/irods_netcdf/packages_2021_03_24/irods-netcdf-icommands-4.2.8.0-centos-7-x86_64.rpm
      - http://people.renci.org/~dmoore/irods_netcdf/packages_2021_03_24/irods-netcdf-server_modules-4.2.8.0-centos-7-x86_64.rpm
    state: present

- name: ensure msiSetAVU microservice is absent
  file:
    path: /var/lib/irods/plugins/microservices/libmsiSetAVU.so
    state: absent
