---
- include_tasks: install_irods_pkg.yml
  vars:
    os: centos{{ ansible_distribution_major_version }}
    pkg: irods-runtime
    pkg_ver: "{{ _irods_version }}"

- name: ensure netcdf plugins not installed
  package:
    name:
      - irods-icommands-netcdf
      - irods-microservice-plugin-netcdf
      - irods-api-plugin-netcdf
    state: absent

- name: ensure netcdf rpms removed
  file:
    path: /root/{{ item }}-1.0-centos{{ ansible_distribution_major_version }}.rpm
    state: absent
  with_items:
    - irods-icommands-netcdf
    - irods-microservice-plugin-netcdf
    - irods-api-plugin-netcdf

- name: ensure msiSetAVU microservice is absent
  file:
    path: /var/lib/irods/plugins/microservices/libmsiSetAVU.so
    state: absent
