---
avra_base_collection: /testing/home/shared/avra
avra_manager: avra_mgr
avra_resource_hierarchy:
  name: avraRes
  type: passthru
  children:
    - name: avra

cereus_collections:
  - /testing/home/shared/cereus

cereus_resource_hierarchy:
  name: cereusRes
  type: passthru
  children:
    - name: cereus

de_job_irods_user: de_job

irods_amqp_host: "{{ groups['amqp'][0] }}"
irods_amqp_user: amqp_admin
irods_amqp_password: password

irods_calliope_project_coll: /testing/home/shared/calliope

irods_default_repl_resource: rs_repl

irods_resource_hierarchies:
  - name: rs_ingest
  - name: rs_repl

irods_server_port_range_end: 20009

pire_manager: pire_mgr
pire_resource_hierarchy:
  name: pireRes
  type: passthru
  children:
    - name: pire

terraref_base_collection: /testing/home/shared/terraref
terraref_manager: terraref_mgr
terraref_resource_hierarchy:
  name: terrarefRes
  type: passthru
  children:
    - name: terraref
