---
version: "2.0"

services:
  amqp:
    image: test-env-base:centos7

  apache:
    build:
      context: .
      dockerfile: apache/Dockerfile

  dbms_configured:
    build:
      context: .
      dockerfile: postgresql/Dockerfile.configured
      args:
        IRODS_RESOURCES: "$IRODS_RS6_NAME:$IRODS_RS6_HOST:$IRODS_VAULT $IRODS_RS7_NAME:$IRODS_RS7_HOST:$IRODS_VAULT"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
    tty: true

  dbms_unconfigured:
    build:
      context: .
      dockerfile: postgresql/Dockerfile.unconfigured
    tty: true
    
  ies_configured:
    build:
      context: .
      dockerfile: ies/Dockerfile.configured
      args:
        DBMS_HOST: "$DBMS_HOST"
        IRODS_DEFAULT_RESOURCE: "$IRODS_DEFAULT_RESOURCE"
        IRODS_HOST: "$IRODS_IES_CONF_HOST"
        IRODS_LAST_EPHEMERAL_PORT: $IRODS_LAST_EPHEMERAL_PORT
        IRODS_SCHEMA_VALIDATION: "$IRODS_SCHEMA_VALIDATION"
        IRODS_SYSTEM_GROUP: "$IRODS_IES_SYSTEM_GROUP"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
    hostname: "$IRODS_IES_CONF_HOST"
    tty: true
    depends_on:
      - amqp
      - dbms_configured

  ies_unconfigured:
    build:
      context: .
      dockerfile: ies/Dockerfile.unconfigured
      args:
        DBMS_HOST: "$DBMS_HOST"
        IRODS_SYSTEM_GROUP: "$IRODS_IES_SYSTEM_GROUP"
    hostname: "$IRODS_IES_UNCONF_HOST"
    tty: true

  load_balancer:
    build:
      context: .
      dockerfile: haproxy/Dockerfile
    depends_on:
      - apache
      - ies_configured

  rs_centos6:
    build:
      context: .
      dockerfile: rs/Dockerfile.centos6
      args:
        IRODS_DEFAULT_RESOURCE: "$IRODS_DEFAULT_RESOURCE"
        IRODS_DEFAULT_VAULT: "$IRODS_VAULT"
        IRODS_HOST: "$IRODS_RS6_HOST"
        IRODS_IES: "$IRODS_IES_CONF_HOST"
        IRODS_LAST_EPHEMERAL_PORT: $IRODS_LAST_EPHEMERAL_PORT
        IRODS_SCHEMA_VALIDATION: "$IRODS_SCHEMA_VALIDATION"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
    cap_add:
      - NET_ADMIN
    hostname: "$IRODS_RS6_HOST"
    tty: true
    depends_on:
      - ies_configured

  rs_centos7:
    build:
      context: .
      dockerfile: rs/Dockerfile.centos7
      args:
        IRODS_IES: "$IRODS_IES_CONF_HOST"
    hostname: "$IRODS_RS7_HOST"
    tty: true
